### ISSUE TITLE
Usage of realm with service account

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/sdk-java#11]
the service account might be in a realm other than the user logging in.
So either assume the service account to be in the default realm or add a parameter for a service acc realm.

**Comment by plettich** [comment]
The service account does an ``/auth`` request before triggering the challenge so shouldn't it suffice to set the service account user to something like ``triggeradmin@other-realm``?

**Comment by nilsbehlen** [comment]
For the sdk, the service account realm should be a distinct optional parameter. Parsing a configuration entry like ``triggeradmin@other-realm`` should be done by the plugin.
